FROM fedora:latest

RUN dnf check-update && dnf upgrade; exit 0

RUN dnf install -y dnf-plugins-core util-linux-user zsh git openssl openssl-devel \
    dotnet java-latest-openjdk-devel gcc clang llvm lld ruby rubygems python3.10 \
    python3-pip poetry bat gitui ripgrep fd-find just tokei jql exa

# Install GitHub CLI
RUN dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo && \
    dnf install -y gh

# Install rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# For proper functioning of poetry
RUN ln -s python3 /usr/bin/python

# Poetry config
RUN poetry config virtualenvs.in-project true

# Rust utilities not present in Fedora repos
RUN source $HOME/.cargo/env && cargo install trunk cargo-audit cargo-edit du-dust rm-improved

# Change default shell
RUN chsh -s /bin/zsh

# zshrc
RUN touch $HOME/.zsh_history
COPY fedora/.zshrc $HOME/.zshrc

# completions
RUN mkdir $HOME/.zsh
RUN mkdir $HOME/.zsh/completions
