name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-podman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: podman build -t fedora-dev-env:test fedora

      - name: Run
        run: podman run --name envtest -d fedora-dev-env:test

      - name: Test
        run: podman exec -i envtest "$(cat ./.github/workflows/test.sh)"

  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make dockerfile
        run: cp fedora/Containerfile fedora/Dockerfile

      - name: Build
        run: docker build -t fedora-dev-env:test fedora

      - name: Run
        run: docker run --name envtest -d fedora-dev-env:test

      - name: Test
        run: docker exec -i envtest "$(cat ./.github/workflows/test.sh)"
