name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-podman:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: podman build fedora

  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Make dockerfile
        run: cp fedora/Containerfile fedora/Dockerfile

      - name: Build
        run: docker build fedora