name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Fetch tags
        run: git fetch --unshallow
      
      - name: Set release version
        run: export RELEASE_VERSION=`git describe --tags --abbrev=0` && echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Build
        run: podman build -t "ghcr.io/saadisave/fedora-dev-env:${{ env.RELEASE_VERSION }}" fedora
      
      - name: Alias
        run: podman image tag "ghcr.io/saadisave/fedora-dev-env:${{ env.RELEASE_VERSION }}" ghcr.io/saadisave/fedora-dev-env:latest

      - name: Login to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u=saadisave --password-stdin

      - name: Push
        run: podman push "ghcr.io/saadisave/fedora-dev-env:${{ env.RELEASE_VERSION }}" && podman push ghcr.io/saadisave/fedora-dev-env:latest
